# Generated by Django 3.2 on 2021-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_href',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
