# Generated by Django 3.2 on 2021-04-26 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('detailed_message', models.TextField()),
                ('date_submitted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
